export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const signupConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};

export const categoryConstants = {
  GET_ALL_CAT_REQUEST: "GET_ALL_CAT_REQUEST",
  GET_ALL_CAT_FAILURE: "GET_ALL_CAT_FAILURE",
  GET_ALL_CAT_SUCCESS: "GET_ALL_CAT_SUCCESS",
};

export const courseConstants = {
  GET_ALL_COURSE_REQUEST: "GET_ALL_COURSE_REQUEST",
  GET_ALL_COURSE_FAILURE: "GET_ALL_COURSE_FAILURE",
  GET_ALL_COURSE_SUCCESS: "GET_ALL_COURSE_SUCCESS",
  GET_COURSE_BY_ID_REQUEST: "GET_COURSE_BY_ID_REQUEST",
  GET_COURSE_BY_ID_FAILURE: "GET_COURSE_BY_ID_FAILURE",
  GET_COURSE_BY_ID_SUCCESS: "GET_COURSE_BY_ID_SUCCESS",
  GET_COURSES_BY_SLUG_REQUEST: "GET_COURSES_BY_SLUG_REQUEST",
  GET_COURSES_BY_SLUG_FAILURE: "GET_COURSES_BY_SLUG_FAILURE",
  GET_COURSES_BY_SLUG_SUCCESS: "GET_COURSES_BY_SLUG_SUCCESS",
};
